apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-places
  labels:
    app.kubernetes.io/part-of: go-places
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: go-places
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: go-places
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: go-places
    spec:
      containers:
      - env:
        - name: MARIADB_USER
          value: dbuser
        - name: MARIADB_PASS
          value: secretpass
        - name: MARIADB_HOST
          value: mariadb
        - name: JAVA_TOOL_OPTIONS
        image: index.docker.io/pvdbleek/go-places-default@sha256:60a94914230ed5fcf995c4beb6585159ec6929fdf3b8a017445697966b388e1a
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

