apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: go-places
  name: go-places
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: go-places